FROM node:20.12

WORKDIR /usr/src/app

COPY package*.json ./

# Removendo node_modules se existir
RUN rm -rf node_modules

# Instalando dependências de sistema necessárias
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Instalando dependências do node
RUN npm install

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "start:dev" ] 